# Generated by Django 3.1.5 on 2021-01-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebuttals',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
