# Generated by Django 3.1.5 on 2021-01-17 06:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_rebuttals_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rebuttals',
            unique_together={('user', 'source')},
        ),
    ]
